version: "3.9"

services:
  engine-python:
    build: ./engine-python
    ports:
      - "50052:50052"
    restart: unless-stopped

  engine-rust:
    build: ./engine-rust
    ports:
      - "50051:50051"
    restart: unless-stopped


